version: "3"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    container_name: nextjs

volumes:
  pgdata:
  cache:
    driver: local
