import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, auth } from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
import Sidebar from "@/components/shared/Sidebar";
import Footer from "@/components/shared/Footer";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isLogged = false;
  const { userId } = auth();

  if (userId) isLogged = true;

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: { colorPrimary: "#0ea5e9" },
        elements: { card: "bg-white dark:bg-secondary" },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute="class" enableSystem defaultTheme="dark">
            <div className="min-h-screen h-full w-full bg-black">
              <Sidebar isLogged={isLogged} />
              {children}
              <Footer />
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
